version: '3.9'

services: 
  
  mysql:
    
    image: mysql

    restart: always
    
    environment:
      - MYSQL_PASSWORD=$DB_PASS
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASS
      - MYSQL_USER=$DB_USER
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:3306
    volumes:
      - db:/database
volumes:
  db:
